In [2]:
import numpy as np

def gauss_pivoteo_parcial(A, b):
    n = len(b)
    # Convertir a float para mayor precisión
    M = np.hstack([A.astype(float), b.reshape(-1, 1)])
    
    print("Matriz inicial:")
    print(np.round(M, 4))
    
    for k in range(n):
        # Pivoteo parcial
        max_row = np.argmax(np.abs(M[k:, k])) + k
        if M[max_row, k] == 0:
            raise ValueError("El sistema no tiene solución única")
            
        if max_row != k:
            M[[k, max_row]] = M[[max_row, k]]
            print(f"\nIntercambio fila {k+1} con {max_row+1}:")
            print(np.round(M, 4))
        
        # Eliminación
        for i in range(k+1, n):
            factor = M[i, k] / M[k, k]
            M[i, k:] -= factor * M[k, k:]
        
        print(f"\nDespués de eliminar columna {k+1}:")
        print(np.round(M, 4))
    
    # Sustitución hacia atrás
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (M[i, -1] - np.dot(M[i, i+1:n], x[i+1:])) / M[i, i]
    
    return x

# Sistema 3x3
A = np.array([[3,   2,  -1],
              [2,  -2,   4],
              [-1, 0.5, -1]])
b = np.array([1, -2, 0])

try:
    solucion = gauss_pivoteo_parcial(A, b)
    print("\nSolución final:")
    print(f"x = {solucion[0]:.6f}")
    print(f"y = {solucion[1]:.6f}")
    print(f"z = {solucion[2]:.6f}")
    
    # Verificación
    print("\nVerificación:")
    print("3x + 2y - z =", 3*solucion[0] + 2*solucion[1] - solucion[2])
    print("2x - 2y +4z =", 2*solucion[0] - 2*solucion[1] + 4*solucion[2])
    print("-x +0.5y -z =", -solucion[0] + 0.5*solucion[1] - solucion[2])
except ValueError as e:
    print(f"Error: {e}")

Matriz inicial:
[[ 3.   2.  -1.   1. ]
 [ 2.  -2.   4.  -2. ]
 [-1.   0.5 -1.   0. ]]

Después de eliminar columna 1:
[[ 3.      2.     -1.      1.    ]
 [ 0.     -3.3333  4.6667 -2.6667]
 [ 0.      1.1667 -1.3333  0.3333]]

Después de eliminar columna 2:
[[ 3.      2.     -1.      1.    ]
 [ 0.     -3.3333  4.6667 -2.6667]
 [ 0.      0.      0.3    -0.6   ]]

Después de eliminar columna 3:
[[ 3.      2.     -1.      1.    ]
 [ 0.     -3.3333  4.6667 -2.6667]
 [ 0.      0.      0.3    -0.6   ]]

Solución final:
x = 1.000000
y = -2.000000
z = -2.000000

Verificación:
3x + 2y - z = 1.0000000000000002
2x - 2y +4z = -1.9999999999999982
-x +0.5y -z = -4.440892098500626e-16
